FROM node:23-alpine

WORKDIR /usr/src/app

COPY ./ ./
COPY ./infra/entrypoint.development.sh ./entrypoint.development.sh

RUN yarn install --frozen-lockfile && \
    chmod u=rwx ./entrypoint.development.sh

ENTRYPOINT "./entrypoint.development.sh"
