FROM node:23-alpine

WORKDIR /usr/src/app

RUN chown -R node /usr/src/app && \
    chmod u=rwx /usr/src/app

COPY ./ ./
COPY ./infra/entrypoint.development.sh ./entrypoint.development.sh

USER node

RUN yarn install --frozen-lockfile

ENTRYPOINT "./entrypoint.development.sh"
